{
 "title": "Engine Performance Dashboard",
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "engine",
    "label": "Engine",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"engine_perf\",\n  tag: \"engine\"\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"CpuUtilDatapointStream\") |> filter(fn: (r) => r.engine == \"${engine}\") |> filter(fn: (r) => r._field == \"idle\" or r._field == \"kernel\" or r._field == \"user\")"
    },
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"CpuUtilDatapointStream\") |> filter(fn: (r) => r.engine == \"${engine}\") |> filter(fn: (r) => r._field == \"idle\" or r._field == \"kernel\" or r._field == \"user\") |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") |> map(fn: (r) => ({ r with cpuUtil: ((float(v: r.kernel) + float(v: r.user)) * 100.0) / (float(v: r.idle) + float(v: r.kernel) + float(v: r.user)) })) |> keep(columns: [\"_time\", \"cpuUtil\"])"
    }
   ]
  },
  {
   "title": "Network Interface Utilization",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"NetworkInterfaceUtilDatapointStream\") |> filter(fn: (r) => r.engine == \"fluentd\") |> filter(fn: (r) => r._field == \"inBytes\" or r._field == \"inPackets\" or r._field == \"outBytes\" or r._field == \"outPackets\")"
    },
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"NetworkInterfaceUtilDatapointStream\") |> filter(fn: (r) => r.engine == \"fluentd\") |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\") |> map(fn: (r) => ({ r with TrafficRatio: float(v: r.outBytes) / float(v: r.inBytes), PacketRatio: if exists r.outPackets and exists r.inPackets and r.inPackets != 0 then float(v: r.outPackets) / float(v: r.inPackets) else 0.0 })) |> keep(columns: [\"_time\", \"TrafficRatio\", \"PacketRatio\"])"
    }
   ]
  },
  {
   "title": "TCP Stats",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"TCPStatsDatapointStream\") |> filter(fn: (r) => r.engine == \"${engine}\") |> filter(fn: (r) => r._field == \"congestionWindowSize\" or r._field == \"inBytes\" or r._field == \"outBytes\" or r._field == \"receiveWindowSize\" or r._field == \"retransmittedSegs\" or r._field == \"roundTripTime\" or r._field == \"sendWindowSize\" or r._field == \"unacknowledgedBytes\" or r._field == \"unsentBytes\")"
    }
   ]
  },
  {
   "title": "Disk Ops",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"DiskOpsDatapointStream\") |> filter(fn: (r) => r.engine == \"fluentd\") |> filter(fn: (r) => r._field == \"avgLatency\" or r._field == \"throughput\" or r._field == \"count\")"
    }
   ]
  },
  {
   "title": "iSCSI Ops",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 36, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"IScsiOpsDatapointStream\") |> filter(fn: (r) => r.engine == \"${engine}\") |> filter(fn: (r) => r._field == \"op\" or r._field == \"avgLatency\" or r._field == \"latency\" or r._field == \"count\" or r._field == \"throughput\")"
    }
   ]
  },
  {
   "title": "NFS Ops",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 36, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"engine_perf\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"NfsOpsDatapointStream\") |> filter(fn: (r) => r.engine == \"${engine}\") |> filter(fn: (r) => r._field == \"op\" or r._field == \"avgLatency\" or r._field == \"latency\" or r._field == \"count\" or r._field == \"throughput\")"
    }
   ]
  }
 ]
}